#!/bin/bash

set -euo pipefail

#--input data/input.csv
nextflow run main.nf --input all-fqs.csv -profile docker,local --clean false -resume \
   --FW_primer "ATGCGATACTTGGTGTGAAT" --RV_primer "GCATATCAATAAGCGGAGGA" --single_end false --retain_untrimmed true \
   --fastq_maxee 0.5 --fastq_minlen 250 --fastq_maxns 0 --fasta_width 0 \
   --minuniquesize 2 --derep_strand "plus" --sizeout \
   --database data/viridiplantae_all_2014.sintax.fa --sintax_strand "both" --sintax_cutoff 0.95 
