name: Run Pipeline Tests

on:
  workflow_dispatch

env:
  NEXTFLOW_VERSION: 23.10.1
  NF_TEST_VERSION: 0.8.4
  AWS_CLI_VERSION: 2.15.19
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace before start
      run: rm -rf $GITHUB_WORKSPACE/*

    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 17.0.9+0
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '17.0.9+9'
        distribution: 'adopt'

    - name: Install nextflow
      run: sudo bash; cd /opt; wget "https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow"; chmod +x nextflow;

    - name: Install nf-test
      run: sudo bash; cd /opt; wget "https://github.com/askimed/nf-test/releases/download/v${NF_TEST_VERSION}/nf-test-${NF_TEST_VERSION}.tar.gz"; tar -xvf "nf-test-${NF_TEST_VERSION}.tar.gz"; chmod +x nf-test; rm "/opt/nf-test-${NF_TEST_VERSION}.tar.gz"

    - name: Install aws cli
      run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip" -o "awscliv2.zip"; unzip awscliv2.zip; sudo ./aws/install --update

    - name: Add software to path
      run: echo "/opt" >> $GITHUB_PATH;

    - name: Run r processing test
      run: nf-test test tests/modules/local/r_processing.nf.test

    - name: Run dereplication test
      run: nf-test test tests/modules/local/vsearch_derep.nf.test

    - name: Run fastq filter test
      run: nf-test test tests/modules/local/vsearch_fastq_filter.nf.test

    - name: Run cutadapt test
      run: nf-test test tests/modules/nf-core/cutadapt/main.nf.test

    - name: Run pear test
      run: nf-test test tests/modules/nf-core/pear/main.nf.test

    - name: Run sintax test
      run: nf-test test tests/modules/nf-core/vsearch/sintax/main.nf.test

    - name: Clean workspace after finish
      run: rm -rf $GITHUB_WORKSPACE/*
