name: Run Pipeline Tests

on:
  workflow_dispatch

env:
  NEXTFLOW_VERSION: 23.10.1
  NF_TEST_VERSION: 0.8.4

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace before start
      run: rm -rf $GITHUB_WORKSPACE/*

    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install nextflow
      run: sudo bash; cd /opt; wget "https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow"; chmod +x nextflow;

    - name: Install nf-test
      run: sudo bash; cd /opt; wget "https://github.com/askimed/nf-test/releases/download/v${NF_TEST_VERSION}/nf-test-${NF_TEST_VERSION}.tar.gz"; tar -xvf "nf-test-${NF_TEST_VERSION}.tar.gz"; chmod +x nf-test; rm "/opt/nf-test-${NF_TEST_VERSION}.tar.gz"

    - name: Add software to path
      run: echo "/opt" >> $GITHUB_PATH;

    - name: Run bash processing test
      run: nf-test test tests/modules/local/processing.nf.test

    - name: Run r processing test
      run: nf-test test tests/modules/local/r_processing.nf.test

    - name: Run dereplication test
      run: nf-test test tests/modules/local/vsearch_derep.nf.test

    - name: Run fastq filter test
      run: nf-test test tests/modules/local/vsearch_fastq_filter.nf.test

    - name: Run cutadapt test
      run: nf-test test tests/modules/nf-core/cutadapt/main.nf.test

    - name: Run pear test
      run: nf-test test tests/modules/nf-core/pear/main.nf.test

    - name: Run sintax test
      run: nf-test test tests/modules/nf-core/vsearch/sintax/main.nf.test

    - name: Clean workspace after finish
      run: rm -rf $GITHUB_WORKSPACE/*
